import sys; sys.path.insert(0, r"j:\Bài đồ án")
from src.database.db_config import DatabaseConnector
conn = DatabaseConnector.get_connection()
cur = conn.cursor()
cur.execute("SELECT user_id, email, account_type, role FROM users WHERE user_id >= 7000 ORDER BY user_id")
for r in cur.fetchall():
    print(r)
print("---")
cur.execute("SELECT COUNT(*) FROM ratings WHERE user_id >= 7000")
print(f"Ratings from users >= 7000: {cur.fetchone()[0]}")
cur.execute("SELECT COUNT(*) FROM movies WHERE movie_id > 3883")
print(f"New movies (id > 3883): {cur.fetchone()[0]}")
cur.execute("SELECT MIN(movie_id), MAX(movie_id) FROM movies WHERE movie_id > 3883")
r = cur.fetchone()
print(f"New movie ID range: {r[0]} - {r[1]}")
cur.close(); conn.close()
